[package]
name = "smithy-bindgen"
version = "0.1.0"
edition = "2021"
authors = [ "wasmcloud Team" ]
license = "Apache-2.0"
description = "macros for binding codegeneration from smithy files"
homepage = "https://github.com/wasmcloud/weld"
repository = "https://github.com/wasmcloud/weld"
documentation = "https://docs.rs/smithy-bindgen"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
atelier_json = "0.2"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
syn = { version = "1.0", features = ["full"] }
tracing = "0.1"
weld-codegen = { version = "0.6.2", path = "../codegen" }
