[package]
name = "wasmbus-rpc"
version = "0.4.3"
edition = "2018"
authors = [ "wasmcloud Team" ]
license = "Apache-2.0"
description = "Runtime library for actors and capability providers"
homepage = "https://github.com/wasmcloud/weld"
repository = "https://github.com/wasmcloud/weld"
documentation = "https://docs.rs/wasmbus-rpc"
readme = "README.md"
resolver = "2"

# don't push build.rs
exclude = [ "build.rs" ]

[features]
# Warning: Don't change serialization - things will break
default = [ "ser_msgpack" ]
BigInteger = [ "num-bigint" ]
BigDecimal = [ "bigdecimal" ]
ser_msgpack = [ "rmp-serde" ]
ser_json = [ ]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
thiserror = "1.0"
toml = "0.5"
log = "0.4"
cfg-if = "1.0"
wasmbus-macros = "0.1"
tokio-timer = "0.2"

#[feature-dependencies]
rmp-serde = { version = "0.15.4", optional = true }

#BigInteger support
num-bigint = { version = "0.4", optional = true }
#BigDecimal support
bigdecimal = { version = "0.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nats = "0.13"
tokio = { version = "1", features = ["full"]}
futures = "0.3"
# work-around "conflicting implementations of From<std::io::Error>" in ratsio build
#ratsio = "0.4.0-alpha.1"
ratsio = { version = "0.4.1", package="ratsio_fork_040" }
once_cell = "1.8"
crossbeam = "0.8"
uuid = { version = "0.8", features=["v4", "serde"] }
wascap = "0.6.0"
ring = "0.16"
pin-utils = "0.1"
data-encoding = "2.3"

[build-dependencies]
weld-codegen = "0.1.17"
