# codegen.toml

[[models]]
# wasmbus-core
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@e69a8b22ce46457dbc48f8bbffd4734b68b739ce/core/wasmcloud-core.smithy"

[[models]]
# wasmbus-model
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@e0f205da8a0e1549497571c3e994a1851480621c/core/wasmcloud-model.smithy"

[rust]
output_dir = "."

[[rust.files]]
path = "src/wasmbus_core.rs"
namespace = "org.wasmcloud.core"
crate = "wasmbus_rpc"

[[rust.files]]
path = "src/wasmbus_model.rs"
namespace = "org.wasmcloud.model"
crate = "wasmbus_rpc"
