# codegen.toml

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@6750c952166d61f71/core/wasmcloud-core.smithy"
[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@374e5bcc63267f3ad/core/wasmcloud-model.smithy"

[rust]
output_dir = "."

[[rust.files]]
path = "src/wasmbus_core.rs"
namespace = "org.wasmcloud.core"
crate = "wasmbus_rpc"

[[rust.files]]
path = "src/wasmbus_model.rs"
namespace = "org.wasmcloud.model"
crate = "wasmbus_rpc"
