# codegen.toml

[[models]]
# wasmbus-core
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core/wasmcloud-core.smithy"

[[models]]
# wasmbus-model
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core/wasmcloud-model.smithy"

[rust]
output_dir = "."

[[rust.files]]
path = "src/wasmbus_core.rs"
namespace = "org.wasmcloud.core"
crate = "wasmbus_rpc"

[[rust.files]]
path = "src/wasmbus_model.rs"
namespace = "org.wasmcloud.model"
crate = "wasmbus_rpc"
